import { buildHmacChain, type AuditLogEntry } from "./hmacChain";
import type { AuditReport } from "./types";

export async function exportReportJson(report: AuditReport): Promise<string> {
  const { entries, keyHex } = await buildHmacChain(report.events);
  return JSON.stringify({ report, hmacChain: { entries, keyHex } }, null, 2);
}

export async function exportReportHtml(report: AuditReport): Promise<Blob> {
  const { entries, keyHex } = await buildHmacChain(report.events);
  const verdictColor =
    report.verdict === "clean"
      ? "#166534"
      : report.verdict === "suspicious"
        ? "#92400e"
        : "#991b1b";
  const verdictBg =
    report.verdict === "clean"
      ? "#f0fdf4"
      : report.verdict === "suspicious"
        ? "#fffbeb"
        : "#fef2f2";

  const eventsHtml =
    report.events.length === 0
      ? "<p>0 events detected during processing.</p>"
      : `<ol>${entries.map((e: AuditLogEntry) => `<li><strong>${e.event.type}</strong>: ${escapeHtml(formatEvent(e))}<br><code>HMAC: ${e.hmac}</code></li>`).join("")}</ol>`;

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>VPE Audit Report — ${escapeHtml(report.toolName)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 700px; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; line-height: 1.6; }
  h1 { font-size: 1.25rem; }
  .verdict { display: inline-block; padding: 0.5rem 1rem; border-radius: 4px; font-weight: 600; background: ${verdictBg}; color: ${verdictColor}; border: 1px solid ${verdictColor}30; }
  .kv { display: flex; justify-content: space-between; gap: 1rem; padding: 0.25rem 0; border-bottom: 1px solid #e5e5e5; }
  .kv .label { color: #525252; font-size: 0.875rem; }
  .kv .value { font-family: monospace; font-size: 0.875rem; word-break: break-all; text-align: right; }
  code { font-size: 0.75rem; color: #525252; }
  .section { margin-top: 1.5rem; }
  .section h2 { font-size: 1rem; margin-bottom: 0.5rem; }
  .disclosure { background: #f5f5f5; padding: 1rem; border-radius: 4px; font-size: 0.875rem; color: #525252; margin-top: 1.5rem; }
  footer { margin-top: 2rem; font-size: 0.75rem; color: #a3a3a3; }
</style>
</head>
<body>
<h1>VPE Audit Report</h1>
<div class="verdict">${escapeHtml(report.verdict.toUpperCase())}</div>

<div class="section">
  <h2>Summary</h2>
  <div class="kv"><span class="label">Tool</span><span class="value">${escapeHtml(report.toolName)}</span></div>
  <div class="kv"><span class="label">Duration</span><span class="value">${report.durationMs}ms</span></div>
  <div class="kv"><span class="label">Input size</span><span class="value">${formatSize(report.inputSizeBytes)}</span></div>
  <div class="kv"><span class="label">Output size</span><span class="value">${formatSize(report.outputSizeBytes)}</span></div>
  <div class="kv"><span class="label">Input SHA-256</span><span class="value">${report.inputSha256Hex}</span></div>
  <div class="kv"><span class="label">Output SHA-256</span><span class="value">${report.outputSha256Hex}</span></div>
  <div class="kv"><span class="label">WebRTC patched</span><span class="value">${report.webrtcPatched ? "Yes" : "No"}</span></div>
  <div class="kv"><span class="label">Monitors</span><span class="value">${report.monitors.join(", ")}</span></div>
  <div class="kv"><span class="label">Timestamp</span><span class="value">${new Date(report.timestamp).toISOString()}</span></div>
</div>

<div class="section">
  <h2>Events (${report.events.length})</h2>
  ${eventsHtml}
</div>

${
  report.cspPolicyActive
    ? `<div class="section"><h2>Active CSP</h2><code>${escapeHtml(report.cspPolicyActive)}</code></div>`
    : ""
}

${
  keyHex
    ? `<div class="section"><h2>HMAC Chain Key</h2><code>${keyHex}</code></div>`
    : ""
}

<div class="disclosure">
  <strong>Residual risks:</strong> This audit cannot detect browser extensions, OS-level compromise, or hardware-level attacks.
  For maximum safety, use Tor Browser on Tails OS with minimal extensions.
</div>

<footer>Generated by PDF Changer VPE. Built by Giuseppe Giona.</footer>
</body>
</html>`;

  return new Blob([html], { type: "text/html" });
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatSize(bytes: number): string {
  if (bytes <= 0) return "0 B";
  const units = ["B", "KB", "MB", "GB"];
  let value = bytes;
  let index = 0;
  while (value >= 1024 && index < units.length - 1) {
    value /= 1024;
    index += 1;
  }
  return `${value.toFixed(index === 0 ? 0 : 1)} ${units[index]}`;
}

function formatEvent(entry: AuditLogEntry): string {
  const e = entry.event;
  switch (e.type) {
    case "network-request":
      return `${e.url} (${e.initiatorType})`;
    case "csp-violation":
      return `${e.blockedURI} blocked by ${e.violatedDirective}`;
    case "dom-injection":
      return `<${e.tagName}> injected${e.src ? ` src="${e.src}"` : ""}`;
  }
}
