name = "pdf-changer-api"
main = "src/index.ts"
compatibility_date = "2026-02-17"

compatibility_flags = ["nodejs_compat"]

[vars]
APP_ORIGIN = "https://pdf-changer.pages.dev"
RP_ID = "pdf-changer.pages.dev"
RP_ORIGIN = "https://pdf-changer.pages.dev"
RP_NAME = "PDF Changer"

[[d1_databases]]
binding = "DB"
database_name = "pdf-changer"
database_id = "771eb824-584c-4473-aef6-93f818fa50fd"
